/**
 * api routes details
 * @author damith
 */

const ApiRoutes = {
  // AUTHENTICATION: "public/user/authentication",
  ADMIN_SIGN_IN: "user/authentication",
  ADMIN_SIGNUP: "user/create/new",
  FORGOT_PASSWORD: "user/reset/password/token",
  RESET_PASSWORD: "user/reset/password",
  RESET_PASSWORD_TOKEN_VALIDATION: "validation/reset/password",
  EXISTING_URL: "user/existing",
  NEW_PRODUCT: "product/create/new",
  GET_PRODUCT: "product/existing",
  UPLOAD_MEDIA: "media/inventory/upload/image",
  VIEW_PRODUCT_BY_STATUS: "product/all",
  DELETE_PHOTO: "media/inventory/delete/image",
  GET_ALL_CATEGORY: "category/all",
  GET_SUB_CATEGORY: "category/subcategory",
  GET_CATEGORY_BY_COMPANY_ID: "company/product/category",
  UPDATE_PRICE: "product/price/update",
  UPDATE_INVENTORY: "product/inventory/update",
  UPDATE_SALES_CHANNEL: "product/sales/channel/update",
  UPDATE_STATUS: "product/status/update",
  GET_PRODUCT_BY_STORE_ID: "product/store/all",
  // EXISTING_COMPANY_NAME: "company/name/existing",
  // EXISTING_COMPANY_EMAIL: "company/email/existing",
  // CREATE_NEW_COMPANY: "company/create/new",
  // CREATE_NEW_COMPANY_USER: "company/user/create/new",
  // CREATE_NEW_VERIFICATION: "verification/email/new",
  // VERIFICATION_EMAIL: "verification/email",
  RESEND_OTP: "resend/email/verification/otp",
  // GET_COMPANY_BY_ID: "company",
  // PUT_COMPANY_PROFILE: "company/profile/update",
  // CREATE_NEW_STORE: "store/new",
  // GET_STORE_BY_COMPANY_ID: "store/company",

  AUTHENTICATION: "user/authentication",
  CREATE_NEW_COMPANY_USER: "create/new/company/user",
  CREATE_NEW_COMPANY: "create/new/company",
  UPDATE_COMPANY_DATA: "update/company/details",
  EXISTING_COMPANY_NAME: "company/name/existing",
  EXISTING_COMPANY_EMAIL: "company/email/existing",
  GET_COMPANY_BY_ID: "get/company/by/id",
  PUT_COMPANY_PROFILE: "update/company/profile",
  CREATE_NEW_VERIFICATION: "create/new/email/verification",
  VERIFICATION_EMAIL: "verify/email",
  CREATE_NEW_STORE: "create/new/store",
  GET_STORE_BY_COMPANY_ID: "get/store/by",
  GET_ALL_STORES: "get/all/stores",
  GET_STORE_AVAILABLE_BY_COMPANY: "get/available/store/by",
  UPDATE_STORE_BANNER_IMAGE: "update/company/store/banner",
  UPDATE_STORE_SERVICEABILITY: "update/store/serviceability",
  UPDATE_STORE_BUSINESS_HOURS: "update/store/business/hour",

  CREATE_COMPANY_PROCESS: "create/company/process",
  GET_COMPANY_PROCESS_BY_COMPANY_ID: "get/company/process/by",
  UPDATE_COMPANY_PROCESS: "update/company/process",

  // ADD_COMPANY_DOCUMENT_DETAILS: "company/add/document",
  // GET_BANK_DETAILS_BY_COMPANY_ID: "company/get/document",

  ADD_COMPANY_DOCUMENT_DETAILS: "add/company/document",
  GET_BANK_DETAILS_BY_COMPANY_ID: "get/document/by",

  // GET_STORE_AVAILABLE_BY_COMPANY: "store/company/available",
  GET_LOCATION_ALL: "location/all",
  CREATE_NEW_WAREHOUSE: "warehouse/create/new",
  // CREATE_NEW_DEPARTMENT: "department/create/new",
  // GET_ALL_DEPARTMENT: "department/all",
  GET_ALL_WAREHOUSE: "warehouse/all",
  // EXISTING_Department_NAME: "department/name/existing",
  EXISTING_WAREHOUSE_NAME: "warehouse/name/existing",

  CREATE_NEW_RESTAURANT_FLOOR: "floor/new",
  EXISTING_RESTAURANT_FLOOR_NAME: "restaurant/floor/name/existing",
  EXISTING_RESTAURANT_FLOOR_NO: "restaurant/floor/no/existing",
  //GET_ALL_RESTAURANT_FLOOR_BY_STORE_ID: "restaurant/floor/all",
  GET_ALL_RESTAURANT_FLOOR_BY_STORE_ID: "floor/all",
  // CREATE_NEW_RESTAURANT_TABLE: "restaurant/floor/table/new",
  CREATE_NEW_RESTAURANT_TABLE: "table/new",
  UPDATE_RESTAURANT_TABLE: "table/update",
  GET_ALL_RESTAURANT_TABLE_BY_FLOOR_ID: "table/floor",
  GET_RESTAURANT_FLOOR_TABLE_COUNT: "floor/table/count",
  CREATE_NEW_RESTAURANT_USER_BY_MOBILE_NO: "restaurant/user/staff/new",
  EXISTING_MOBILE_NO: "restaurant/user/staff/existing",
  GET_ALL_RESTAURANT_STAFF: "restaurant/user/staff/get/all",

  CREATE_NEW_GUEST: "guest/new",
  GET_GUEST_BY_ID: "guest",
  GET_ALL_GUEST_BY_PAGE: "guest/all",
  UPDATE_GUEST_TAG: "guest/tag/update",
  UPDATE_GUEST_BASIC_INFO: "guest/profile/basic/info/update",
  UPDATE_GUEST_PERSONAL_INFO: "guest/profile/personal/info/update",

  GET_ALL_TAGS: "tag/all",

  CREATE_NEW_MENU: "create/new/menu",
  UPDATE_MENUS: "update/menu",
  GET_ALL_MENUS_BY_STORE_ID: "get/menu/by",
  EXISTING_MENU_NAME: "existing/menu/name",

  CREATE_NEW_DEPARTMENT: "create/new/department",
  ADD_NEW_DEPARTMENT: "add/new/department",
  GET_ALL_DEPARTMENT_BY_STORE_ID: "get/department/by/id",
  ADD_NEW_ROLE: "add/new/role",
  EXISTING_DEPARTMENT_NAME: "existing/department/name",
  EXISTING_ROLE_NAME: "existing/role/name",

  CREATE_NEW_STAFF_MEMBER: "create/new/staff/employee",
  UPDATE_STAFF_MEMBER_PERSONAL: "update/employee/personal",
  UPDATE_STAFF_MEMBER_ACCESS: "update/employee/access",
  UPDATE_STAFF_MEMBER_LOCATION: "update/employee/location",
  UPDATE_STAFF_MEMBER_EMERGENCY: "update/employee/emergency",
  UPDATE_STAFF_MEMBER_EMPLOYEMENT_DETAILS: "update/employment/details",
  UPDATE_STAFF_MEMBER_EMPLOYEMENT_SHIFT: "update/employment/shift",
  GET_ALL_STAFF_BY_STORE_ID: "get/all/staff/by",
};

export default ApiRoutes;
